discovery_mars/config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  post :track, to: 'pages#track', as: :track_pages
end

discovery_mars/app/models/land.rb
class Land < ActiveRecord::Base
  has_many :rovers

  validates_numericality_of :x, greater_than: 0, only_integer: true
  validates_numericality_of :y, greater_than: 0, only_integer: true

  def bounds
    [x, y]
  end

  def bounds=(value)
    self.x = value[0]
    self.y = value[1]
  end

  def self.parse_order_from_text(orders)
    lines = orders.lines.map { |l| l.strip.chomp }

    # Init land
    begin
      land_bounds = lines.shift
      bounds = land_bounds.scan(/^(-?\d+) (-?\d+)$/)[0]
      bounds.map!(&:to_i)
      land = Land.new(bounds: bounds)
    rescue => e
      raise "It wasn't possible to obtain the land bounds"
    end

    # Create rovers
    if land.valid?
      lines.each_slice(2) do |rover_lines|
        begin
          location = rover_lines[0].downcase.scan(/^(-?\d+) (-?\d+) (n|w|e|s)$/)[0]
          location[0] = location[0].to_i
          location[1] = location[1].to_i
          actions = rover_lines[1].to_s.downcase.tr('^(l|r|m)', '').split('')
          rover = land.new_rover_from_bounds location, actions
          land.rovers << rover
        rescue => e
          raise 'Failed parse rover orders'
        end
      end
    end

    land
  end

  def new_rover_from_bounds(location, actions = [])
    rover = Rover.new(land: self, location: location)
    rover.track actions if actions.present?
    rover
  end
end

discovery_mars/app/models/rover.rb
class Rover < ActiveRecord::Base
  extend Enumerize

  belongs_to :land

  validates_numericality_of :x, greater_than_or_equal_to: 0, only_integer: true
  validates_numericality_of :y, greater_than_or_equal_to: 0, only_integer: true
  validates_presence_of :way
  validates_presence_of :land
  validate :validate_position

  enumerize :way, in: [:n, :e, :s, :w]

  def position
    [x, y]
  end

  def location
    [x, y, way]
  end

  def location=(value)
    self.x = value[0]
    self.y = value[1]
    self.way = value[2]
  end

  def track(actions)
    actions.each do |action|
      break unless valid?
      case action.to_sym
      when :l
        turn_left
      when :r
        turn_right
      when :m
        move
        end
    end
  end

  protected

  def turn_left
    case way.to_sym
    when :n
      self.way = :w
    when :w
      self.way = :s
    when :s
      self.way = :e
    when :e
      self.way = :n
      end
  end

  def turn_right
    case way.to_sym
    when :n
      self.way = :e
    when :e
      self.way = :s
    when :s
      self.way = :w
    when :w
      self.way = :n
      end
  end

  def move
    case way.to_sym
    when :n
      self.y += 1
    when :e
      self.x += 1
    when :s
      self.y -= 1
    when :w
      self.x -= 1
      end
  end

  private

  def validate_position
    errors.add(:position, 'out of land limits') if self.x < 0 || self.y < 0 || x > land.x || y > land.y
  end
end

discovery_mars/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

discovery_mars/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout proc { false if request.xhr? }

  def index
  end

  def track
    @land = Land.parse_order_from_text params[:track_orders] if params[:track_orders]
  rescue => e
    render json: { error: e.message }, status: :bad_request
  end
end

discovery_mars/app/helpers/application_helper.rb
module ApplicationHelper
end

discovery_mars/app/helpers/pages_helper.rb
module PagesHelper
end

discovery_mars/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Discovery Mars</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="page-header">
      <h1>Discovery Mars</h1>
    </div>

    <%= yield %>

    <hr />
    <footer class="footer">
      <p class="text-muted text-left pull-left">&copy; Francisco Sobrino <%= Date.today.year %></p>
      <%= link_to "https://www.dropbox.com/s/gpqit9pb28agcs3/2015-11-13_francisco_sobrino_rey.pdf?dl=1", class: "text-muted text-right pull-right" do %>
        <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
      <% end %>

    </footer>

  </div>
  
  <%= insert_paloma_hook %>

</body>
</html>

discovery_mars/app/views/pages/index.html.erb
<div class="row">
  <div class="col-lg-6 col-md-12">
    <%= image_tag "rover_header.jpg", alt: "http://www.truthdig.com/cartoon/item/nasa_curiosity_20120810", class: "img-responsive center-block" %>
  </div>

   <div class="col-lg-6 col-md-12">
    <%= form_tag track_pages_path, remote: true do %>
      <div class="form-group">
        <%= label_tag :track_orders, "Track orders" %>
        <%= text_area_tag :track_orders, nil, class: "form-control", rows: 8 %>
      </div>

      <%= submit_tag nil, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

<div class="modal fade" data-dom="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Rovers positions</h4>
      </div>
      <div class="modal-body" data-dom="results">      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

discovery_mars/app/views/pages/track.html.erb
<div>
  <h5>Land bounds</h5>
  <p><%= @land.bounds.join(', ') %></p>
  <% if !@land.valid? && @land.errors[:rovers].empty? %>
    <p>Errors</p>
    <ul class="list-unstyled">
      <% @land.errors.to_h.except(:rovers).each do |attribute, error| %>
        <li><%= "#{attribute.capitalize}: #{error}" %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<% unless @land.rovers.empty? %>
  <div>
    <h5>Rovers </h5>
    <ul>
      <% @land.rovers.each do |rover| %>
        <li>
        <% if rover.valid? %>
          <%= rover.location.join(' ').upcase %>
        <% else %>
          <ul class="list-unstyled">
            <% rover.errors.each do |attribute, error| %>
              <li><%= "#{attribute.capitalize}: #{error}" %></li>
            <% end %>
          </ul>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>